### ISSUE TITLE
ToplevelState() not working with Isabelle2021

### ISSUE THREAD

**Issue by luan-xiaokun** [dominique-unruh/scala-isabelle#12]
The following two ways of creating ToplevelState variable are inconsistent, the first one works fine with Isabelle2021, but the second one throws an exception.

```scala
// first one
// as in https://github.com/dominique-unruh/scala-isabelle/blob/master/src/test/scala/de/unruh/isabelle/experiments/TheoryManager.scala
val init_toplevel = compileFunction0[ToplevelState]("Toplevel.init_toplevel")
var toplevel = init_toplevel().force.retrieveNow

// second one
// with implicit Isabelle defined
val toplevel = ToplevelState()
```

The second way is supported after 0.4.2 release, and it works fine with version 2021-1 and  2022, but not with 2021. The error messages are as follows:

```
[scala-execution-context-global-26] ERROR de.unruh.isabelle.mlvalue.MLValue - Error while compiling value "(E_Option o Option.map (E_String)) ((Isabelle_System.isabelle_identifier()) : ((string) option))":
de.unruh.isabelle.control.IsabelleMLException: ML error:
Value or constructor (isabelle_identifier) has not been declared in structure Isabelle_System, when compiling let open Control_Isabelle val result = ((E_Option o Option.map (E_String)) ((Isabelle_System.isabelle_identifier()) : ((string) option))) in store 57 result end
	at de.unruh.isabelle.control.IsabelleMLException$.unsafeFromId(Isabelle.scala:1076)
	at de.unruh.isabelle.control.DefaultExceptionManager.createException(ExceptionManager.scala:43)
	at de.unruh.isabelle.control.Isabelle.$anonfun$parseIsabelle$3(Isabelle.scala:292)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Basically, it complains that `Isabelle_System.isabelle_identifier` is not defined.
Indeed, `isabelle_identifier` is not declared in Isabelle_System (src/Pure/System/isabelle_system.ML) in Isabelle2021, but the only place that it is accessed seems to be in https://github.com/dominique-unruh/scala-isabelle/blob/545fe4e66c4a50beeb1f01137ad646e668beba05/src/main/scala/de/unruh/isabelle/mlvalue/Version.scala#L35-L40

which is wrapped within a try block. So, not sure if this is a bug of scala-isabelle or Isabelle2021.

**Comment by dominique-unruh** [comment]
As it turns out, `ToplevelState()` also works with Isabelle2021. The error message you see is a spurious (and harmless) side effect in the log of the code that detects the current Isabelle-version. It does not affect the functionality of the code; you can ignore it.

I have removed this error message in 9a487d0fe1ffe7947d94ad9747fe5ca7af6f7ebb.
